#!/bin/bash

echo "1" > /sys/devices/system/cpu/cpufreq/boost

cpufreq-set -c 0 -g ondemand
cpufreq-set -c 1 -g ondemand
cpufreq-set -c 2 -g ondemand
cpufreq-set -c 3 -g ondemand
cpufreq-set -c 4 -g ondemand
cpufreq-set -c 5 -g ondemand
cpufreq-set -c 6 -g ondemand
cpufreq-set -c 7 -g ondemand
cpufreq-set -c 8 -g ondemand
cpufreq-set -c 9 -g ondemand
cpufreq-set -c 10 -g ondemand
cpufreq-set -c 11 -g ondemand
cpufreq-set -c 12 -g ondemand
cpufreq-set -c 13 -g ondemand
cpufreq-set -c 14 -g ondemand
cpufreq-set -c 15 -g ondemand
cpufreq-set -c 16 -g ondemand
cpufreq-set -c 17 -g ondemand
cpufreq-set -c 18 -g ondemand
cpufreq-set -c 19 -g ondemand
cpufreq-set -c 20 -g ondemand
cpufreq-set -c 21 -g ondemand
cpufreq-set -c 22 -g ondemand
cpufreq-set -c 23 -g ondemand
cpufreq-set -c 24 -g ondemand
cpufreq-set -c 25 -g ondemand
cpufreq-set -c 26 -g ondemand
cpufreq-set -c 27 -g ondemand
cpufreq-set -c 28 -g ondemand
cpufreq-set -c 29 -g ondemand
cpufreq-set -c 30 -g ondemand
cpufreq-set -c 31 -g ondemand
cpufreq-set -c 32 -g ondemand
cpufreq-set -c 33 -g ondemand
cpufreq-set -c 34 -g ondemand
cpufreq-set -c 35 -g ondemand
cpufreq-set -c 36 -g ondemand
cpufreq-set -c 37 -g ondemand
cpufreq-set -c 38 -g ondemand
cpufreq-set -c 39 -g ondemand
cpufreq-set -c 40 -g ondemand
cpufreq-set -c 41 -g ondemand
cpufreq-set -c 42 -g ondemand
cpufreq-set -c 43 -g ondemand
cpufreq-set -c 44 -g ondemand
cpufreq-set -c 45 -g ondemand
cpufreq-set -c 46 -g ondemand
cpufreq-set -c 47 -g ondemand
cpufreq-set -c 48 -g ondemand
cpufreq-set -c 49 -g ondemand
cpufreq-set -c 50 -g ondemand
cpufreq-set -c 51 -g ondemand
cpufreq-set -c 52 -g ondemand
cpufreq-set -c 53 -g ondemand
cpufreq-set -c 54 -g ondemand
cpufreq-set -c 55 -g ondemand
cpufreq-set -c 56 -g ondemand
cpufreq-set -c 57 -g ondemand
cpufreq-set -c 58 -g ondemand
cpufreq-set -c 59 -g ondemand
cpufreq-set -c 60 -g ondemand
cpufreq-set -c 61 -g ondemand
cpufreq-set -c 62 -g ondemand
cpufreq-set -c 63 -g ondemand
